coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: false

fixes:
  - "/__w/druid/druid/::"

comment:
  layout: "header, diff, files"
  behavior: default
