name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        config:
          - compiler: msvc
            os: windows-latest
            preset: x64-windows-msvc-debug
          - compiler: clang
            os: macos-latest
            preset: arm64-osx-clang-release

    runs-on: ${{ matrix.config.os }}

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg_cache
      VCPKG_BINARY_SOURCES: "default"

    steps:
      - uses: actions/checkout@v4

      - name: vcpkg-cache-directory
        run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        shell: bash

      - name: vcpkg-cache-restore
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: install-tools-windows
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: |
          choco install -y cmake ninja
        shell: bash

      - name: install-tools-macos
        if: ${{ matrix.config.os == 'macos-latest' }}
        run: |
          # Install LLVM 20 via Homebrew
          brew install llvm@20 ninja cmake
          echo "/opt/homebrew/opt/llvm@20/bin" >> $GITHUB_PATH
        shell: bash

      - name: setup-msvc
        if: ${{ matrix.config.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: cmake-configure
        run: cmake --preset ${{ matrix.config.preset }}
        shell: bash

      - name: cmake-build
        run: cmake --build --preset ${{ matrix.config.preset }}
        shell: bash
