name: linux

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        config:
          - preset: x64-linux-gcc-release
            compiler: gcc
          - preset: x64-linux-clang-debug
            compiler: clang

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/druidengine/images/ubuntu-dev:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,github,readwrite"

    steps:
      - uses: actions/checkout@v4

      - name: nuget authentication
        run: |
          mono `vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source https://nuget.pkg.github.com/druidengine/index.json \
          -name github \
          -username ${{ github.actor }} \
          -password ${{ secrets.GITHUB_TOKEN }} \
          -storepasswordincleartext

      - name: cmake-configure
        run: cmake --preset ${{ matrix.config.preset }}

      - name: cmake-build
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: cmake-test
        run: ctest --preset ${{ matrix.config.preset }}
