name: osx

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        config:
          - preset: arm64-osx-clang-release

    runs-on: macos-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;nuget,github,readwrite"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: initialize vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: install-tools-macos
        run: |
          brew install llvm@20 ninja cmake mono
          brew install autoconf autoconf-archive automake libtool
          echo "/opt/homebrew/opt/llvm@20/bin" >> $GITHUB_PATH

      - name: nuget authentication
        run: |
          mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source https://nuget.pkg.github.com/druidengine/index.json \
          -name github \
          -username ${{ github.actor }} \
          -password ${{ secrets.GITHUB_TOKEN }} \
          -storepasswordincleartext

      - name: cmake-configure
        run: cmake --preset ${{ matrix.config.preset }}

      - name: cmake-build
        run: cmake --build --preset ${{ matrix.config.preset }}

      - name: cmake-test
        run: ctest --preset ${{ matrix.config.preset }}
